---
- name: "Create a Backend app directory"
  file:
    path: ~/backend
    state: directory

- name: "update local apt repo"
  become: true
  apt:
    update_cache: yes

- name: "upgrade apt packages"
  become: true
  apt:
    upgrade: yes

- name: "remove stale dependencies"
  become: true
  apt:
    autoremove: yes

- name: "install nodejs and npm"
  become: true
  apt: 
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
- name: "install pm2"
  become: true
  npm: 
    name: pm2
    global: yes
    production: yes
    state: present
- name: "Unarchive backend files"
  unarchive:
    src: ~/project/.circleci/ansible/files/artifact.tar.gz
    dest: ~/backend

- name: "Run app"
  become: true
  shell: |
    cd ~/backend
    npm install
    npm run build
    pm2 stop all
    pm2 start npm -- start

# - name: "Executing node app with PM2"
#   shell: |
#     cd ~/backend/dist
#     cd ../
#     npm install
#     npm run build
#     sudo npm install forever -g
#     sudo npm install ts-node -g
#     forever start -c "ts-node -r tsconfig-paths/register -r dotenv/config src/mais.ts"
#   register: execute_node

# - name: print message
#   debug: 
#     msg: "{{ execute_node.stdout_lines }}"

# - name: "Configure PM2 to start as a service"
#   become: true
#   shell: |
#     env: PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu